// Pre-scored applicants used to populate the demo session, so a first-time
// visitor lands on a dashboard with data instead of an empty state.
//
// These are real outputs from the model API (POST /api/credit_risk/analyze) on
// public/templates/sample.csv, captured so the demo works even if the model
// service is cold-starting. The 12 applicants are picked to give an even spread
// across all four risk bands.

const DEMO_APPLICANTS = [
  {
    "age": 28,
    "applicant_id": "F8223",
    "application_date": "2024-10-26",
    "application_to_income_ratio": 0.1807,
    "avg_transaction_amount_inr": 2434,
    "banking_relationship_years": 12.0,
    "city": "Surat",
    "consent_status": "Full Consent",
    "daily_mobile_hours": 3.8,
    "debt_service_coverage": 2.8442,
    "digital_payment_adoption_score": 46,
    "education_level": "Diploma",
    "employment_type": "Salaried",
    "family_size": 4,
    "financial_health_score": 64,
    "gender": "Female",
    "income_to_expense_ratio": 1.468,
    "interest_rate": 18.14,
    "loan_amount_applied_inr": 185069,
    "loan_type": "personal loan",
    "loan_type_auto_loan": 0,
    "loan_type_business_loan": 0,
    "loan_type_credit_card": 0,
    "loan_type_education_loan": 0,
    "loan_type_gold_loan": 0,
    "loan_type_home_loan": 0,
    "loan_type_personal_loan": 1,
    "loan_utilization_ratio": 0.5579,
    "location_stability_score": 120,
    "location_type": "Metro",
    "marital_status": "Married",
    "mobile_app_usage_intensity_score": 42,
    "mobile_banking_usage_score": 95,
    "monthly_business_revenue_inr": 0,
    "monthly_digital_transactions": 35,
    "monthly_expenses_inr": 58124,
    "monthly_income_inr": 85326,
    "monthly_savings_inr": 24474,
    "monthly_utility_bills_inr": 35792,
    "number_of_dependents": 2,
    "outstanding_loan_amount_inr": 103248,
    "payment_reliability_score": 87,
    "probability_of_default": 0.0662,
    "property_value_inr": 0,
    "repayment_ability_score": 64,
    "risk_category": "Low Risk",
    "risk_score": 6.6,
    "social_media_accounts_count": 2,
    "spouse_income_inr": 63376,
    "stability_index": 60,
    "timeliness_score": 93,
    "total_assets": 313748,
    "total_investments_inr": 0,
    "utility_payment_regularity_score": 95,
    "vehicle_value_inr": 313748,
    "years_current_employment": 10.0
  },
  {
    "age": 27,
    "applicant_id": "A7887",
    "application_date": "2024-06-04",
    "application_to_income_ratio": 0.3352,
    "avg_transaction_amount_inr": 2610,
    "banking_relationship_years": 11.0,
    "city": "Bharuch",
    "consent_status": "Full Consent",
    "daily_mobile_hours": 7.4,
    "debt_service_coverage": 0.9867,
    "digital_payment_adoption_score": 75,
    "education_level": "Post Graduate",
    "employment_type": "Salaried",
    "family_size": 1,
    "financial_health_score": 43,
    "gender": "Male",
    "income_to_expense_ratio": 1.4066,
    "interest_rate": 30.22,
    "loan_amount_applied_inr": 180989,
    "loan_type": "credit card",
    "loan_type_auto_loan": 0,
    "loan_type_business_loan": 0,
    "loan_type_credit_card": 1,
    "loan_type_education_loan": 0,
    "loan_type_gold_loan": 0,
    "loan_type_home_loan": 0,
    "loan_type_personal_loan": 0,
    "loan_utilization_ratio": 0.7401,
    "location_stability_score": 120,
    "location_type": "Tier2",
    "marital_status": "Single",
    "mobile_app_usage_intensity_score": 60,
    "mobile_banking_usage_score": 95,
    "monthly_business_revenue_inr": 0,
    "monthly_digital_transactions": 51,
    "monthly_expenses_inr": 31992,
    "monthly_income_inr": 45000,
    "monthly_savings_inr": 11014,
    "monthly_utility_bills_inr": 3062,
    "number_of_dependents": 0,
    "outstanding_loan_amount_inr": 133941,
    "payment_reliability_score": 78,
    "probability_of_default": 0.1206,
    "property_value_inr": 0,
    "repayment_ability_score": 49,
    "risk_category": "Low Risk",
    "risk_score": 12.1,
    "social_media_accounts_count": 3,
    "spouse_income_inr": 0,
    "stability_index": 63,
    "timeliness_score": 81,
    "total_assets": 0,
    "total_investments_inr": 0,
    "utility_payment_regularity_score": 87,
    "vehicle_value_inr": 0,
    "years_current_employment": 9.0
  },
  {
    "age": 44,
    "applicant_id": "B1995",
    "application_date": "2025-01-05",
    "application_to_income_ratio": 0.3934,
    "avg_transaction_amount_inr": 6766,
    "banking_relationship_years": 28.0,
    "city": "Jamnagar",
    "consent_status": "Full Consent",
    "daily_mobile_hours": 4.4,
    "debt_service_coverage": 2.3466,
    "digital_payment_adoption_score": 42,
    "education_level": "Diploma",
    "employment_type": "Salaried",
    "family_size": 2,
    "financial_health_score": 74,
    "gender": "Female",
    "income_to_expense_ratio": 1.6936,
    "interest_rate": 11.43,
    "loan_amount_applied_inr": 418003,
    "loan_type": "auto loan",
    "loan_type_auto_loan": 1,
    "loan_type_business_loan": 0,
    "loan_type_credit_card": 0,
    "loan_type_education_loan": 0,
    "loan_type_gold_loan": 0,
    "loan_type_home_loan": 0,
    "loan_type_personal_loan": 0,
    "loan_utilization_ratio": 0.4062,
    "location_stability_score": 120,
    "location_type": "Tier1",
    "marital_status": "Married",
    "mobile_app_usage_intensity_score": 40,
    "mobile_banking_usage_score": 95,
    "monthly_business_revenue_inr": 0,
    "monthly_digital_transactions": 35,
    "monthly_expenses_inr": 52285,
    "monthly_income_inr": 88549,
    "monthly_savings_inr": 33204,
    "monthly_utility_bills_inr": 5569,
    "number_of_dependents": 0,
    "outstanding_loan_amount_inr": 169787,
    "payment_reliability_score": 85,
    "probability_of_default": 0.0459,
    "property_value_inr": 0,
    "repayment_ability_score": 76,
    "risk_category": "Low Risk",
    "risk_score": 4.6,
    "social_media_accounts_count": 2,
    "spouse_income_inr": 0,
    "stability_index": 77,
    "timeliness_score": 95,
    "total_assets": 292849,
    "total_investments_inr": 292849,
    "utility_payment_regularity_score": 95,
    "vehicle_value_inr": 0,
    "years_current_employment": 26.0
  },
  {
    "age": 45,
    "applicant_id": "A7205",
    "application_date": "2025-05-15",
    "application_to_income_ratio": 1.2103,
    "avg_transaction_amount_inr": 4307,
    "banking_relationship_years": 16.3,
    "city": "Anand",
    "consent_status": "Full Consent",
    "daily_mobile_hours": 4.8,
    "debt_service_coverage": 1.0264,
    "digital_payment_adoption_score": 71,
    "education_level": "Post Graduate",
    "employment_type": "Business Owner",
    "family_size": 1,
    "financial_health_score": 95,
    "gender": "Female",
    "income_to_expense_ratio": 2.7595,
    "interest_rate": 17.55,
    "loan_amount_applied_inr": 2000000,
    "loan_type": "personal loan",
    "loan_type_auto_loan": 0,
    "loan_type_business_loan": 0,
    "loan_type_credit_card": 0,
    "loan_type_education_loan": 0,
    "loan_type_gold_loan": 0,
    "loan_type_home_loan": 0,
    "loan_type_personal_loan": 1,
    "loan_utilization_ratio": 0.4957,
    "location_stability_score": 120,
    "location_type": "Tier2",
    "marital_status": "Single",
    "mobile_app_usage_intensity_score": 41,
    "mobile_banking_usage_score": 84,
    "monthly_business_revenue_inr": 238248,
    "monthly_digital_transactions": 28,
    "monthly_expenses_inr": 49905,
    "monthly_income_inr": 137712,
    "monthly_savings_inr": 84797,
    "monthly_utility_bills_inr": 5422,
    "number_of_dependents": 0,
    "outstanding_loan_amount_inr": 991384,
    "payment_reliability_score": 43,
    "probability_of_default": 0.2254,
    "property_value_inr": 3314585,
    "repayment_ability_score": 66,
    "risk_category": "Medium Risk",
    "risk_score": 22.5,
    "social_media_accounts_count": 2,
    "spouse_income_inr": 0,
    "stability_index": 79,
    "timeliness_score": 84,
    "total_assets": 5192671,
    "total_investments_inr": 1591706,
    "utility_payment_regularity_score": 92,
    "vehicle_value_inr": 286380,
    "years_current_employment": 2.0
  },
  {
    "age": 24,
    "applicant_id": "E9597",
    "application_date": "2024-08-26",
    "application_to_income_ratio": 1.4176,
    "avg_transaction_amount_inr": 1522,
    "banking_relationship_years": 8.0,
    "city": "Navsari",
    "consent_status": "Full Consent",
    "daily_mobile_hours": 7.0,
    "debt_service_coverage": 0.9369,
    "digital_payment_adoption_score": 75,
    "education_level": "Graduate",
    "employment_type": "Salaried",
    "family_size": 1,
    "financial_health_score": 50,
    "gender": "Female",
    "income_to_expense_ratio": 1.5631,
    "interest_rate": 12.16,
    "loan_amount_applied_inr": 765480,
    "loan_type": "education loan",
    "loan_type_auto_loan": 0,
    "loan_type_business_loan": 0,
    "loan_type_credit_card": 0,
    "loan_type_education_loan": 1,
    "loan_type_gold_loan": 0,
    "loan_type_home_loan": 0,
    "loan_type_personal_loan": 0,
    "loan_utilization_ratio": 0.25,
    "location_stability_score": 120,
    "location_type": "Tier2",
    "marital_status": "Single",
    "mobile_app_usage_intensity_score": 89,
    "mobile_banking_usage_score": 95,
    "monthly_business_revenue_inr": 0,
    "monthly_digital_transactions": 61,
    "monthly_expenses_inr": 28789,
    "monthly_income_inr": 45000,
    "monthly_savings_inr": 14942,
    "monthly_utility_bills_inr": 3174,
    "number_of_dependents": 0,
    "outstanding_loan_amount_inr": 191370,
    "payment_reliability_score": 60,
    "probability_of_default": 0.2813,
    "property_value_inr": 0,
    "repayment_ability_score": 46,
    "risk_category": "Medium Risk",
    "risk_score": 28.1,
    "social_media_accounts_count": 3,
    "spouse_income_inr": 0,
    "stability_index": 38,
    "timeliness_score": 72,
    "total_assets": 0,
    "total_investments_inr": 0,
    "utility_payment_regularity_score": 95,
    "vehicle_value_inr": 0,
    "years_current_employment": 6.0
  },
  {
    "age": 22,
    "applicant_id": "B3735",
    "application_date": "2024-10-12",
    "application_to_income_ratio": 0.1924,
    "avg_transaction_amount_inr": 1585,
    "banking_relationship_years": 0.5,
    "city": "Anand",
    "consent_status": "Full Consent",
    "daily_mobile_hours": 7.7,
    "debt_service_coverage": 10.3644,
    "digital_payment_adoption_score": 72,
    "education_level": "Graduate",
    "employment_type": "Salaried",
    "family_size": 2,
    "financial_health_score": 53,
    "gender": "Female",
    "income_to_expense_ratio": 2.1182,
    "interest_rate": 18.4,
    "loan_amount_applied_inr": 163803,
    "loan_type": "personal loan",
    "loan_type_auto_loan": 0,
    "loan_type_business_loan": 0,
    "loan_type_credit_card": 0,
    "loan_type_education_loan": 0,
    "loan_type_gold_loan": 0,
    "loan_type_home_loan": 0,
    "loan_type_personal_loan": 1,
    "loan_utilization_ratio": 0.25,
    "location_stability_score": 69,
    "location_type": "Tier2",
    "marital_status": "Married",
    "mobile_app_usage_intensity_score": 63,
    "mobile_banking_usage_score": 95,
    "monthly_business_revenue_inr": 0,
    "monthly_digital_transactions": 47,
    "monthly_expenses_inr": 33497,
    "monthly_income_inr": 70952,
    "monthly_savings_inr": 35379,
    "monthly_utility_bills_inr": 10026,
    "number_of_dependents": 0,
    "outstanding_loan_amount_inr": 40950,
    "payment_reliability_score": 49,
    "probability_of_default": 0.2161,
    "property_value_inr": 0,
    "repayment_ability_score": 67,
    "risk_category": "Medium Risk",
    "risk_score": 21.6,
    "social_media_accounts_count": 3,
    "spouse_income_inr": 47566,
    "stability_index": 25,
    "timeliness_score": 41,
    "total_assets": 217241,
    "total_investments_inr": 0,
    "utility_payment_regularity_score": 95,
    "vehicle_value_inr": 217241,
    "years_current_employment": 4.0
  },
  {
    "age": 31,
    "applicant_id": "B5097",
    "application_date": "2025-04-21",
    "application_to_income_ratio": 1.633,
    "avg_transaction_amount_inr": 3072,
    "banking_relationship_years": 15.0,
    "city": "Bharuch",
    "consent_status": "Full Consent",
    "daily_mobile_hours": 5.7,
    "debt_service_coverage": 0.3089,
    "digital_payment_adoption_score": 74,
    "education_level": "Graduate",
    "employment_type": "Salaried",
    "family_size": 2,
    "financial_health_score": 66,
    "gender": "Male",
    "income_to_expense_ratio": 1.7778,
    "interest_rate": 11.32,
    "loan_amount_applied_inr": 1500000,
    "loan_type": "auto loan",
    "loan_type_auto_loan": 1,
    "loan_type_business_loan": 0,
    "loan_type_credit_card": 0,
    "loan_type_education_loan": 0,
    "loan_type_gold_loan": 0,
    "loan_type_home_loan": 0,
    "loan_type_personal_loan": 0,
    "loan_utilization_ratio": 0.8511,
    "location_stability_score": 120,
    "location_type": "Tier2",
    "marital_status": "Married",
    "mobile_app_usage_intensity_score": 82,
    "mobile_banking_usage_score": 95,
    "monthly_business_revenue_inr": 0,
    "monthly_digital_transactions": 56,
    "monthly_expenses_inr": 43057,
    "monthly_income_inr": 76545,
    "monthly_savings_inr": 32859,
    "monthly_utility_bills_inr": 8921,
    "number_of_dependents": 0,
    "outstanding_loan_amount_inr": 1276682,
    "payment_reliability_score": 35,
    "probability_of_default": 0.5525,
    "property_value_inr": 859700,
    "repayment_ability_score": 48,
    "risk_category": "High Risk",
    "risk_score": 55.3,
    "social_media_accounts_count": 5,
    "spouse_income_inr": 35120,
    "stability_index": 69,
    "timeliness_score": 79,
    "total_assets": 1497911,
    "total_investments_inr": 379993,
    "utility_payment_regularity_score": 61,
    "vehicle_value_inr": 258218,
    "years_current_employment": 13.0
  },
  {
    "age": 32,
    "applicant_id": "E5255",
    "application_date": "2024-12-03",
    "application_to_income_ratio": 1.8175,
    "avg_transaction_amount_inr": 2916,
    "banking_relationship_years": 16.0,
    "city": "Jamnagar",
    "consent_status": "Full Consent",
    "daily_mobile_hours": 7.4,
    "debt_service_coverage": 0.2437,
    "digital_payment_adoption_score": 69,
    "education_level": "Graduate",
    "employment_type": "Professional",
    "family_size": 1,
    "financial_health_score": 33,
    "gender": "Female",
    "income_to_expense_ratio": 1.3199,
    "interest_rate": 12.44,
    "loan_amount_applied_inr": 1686203,
    "loan_type": "education loan",
    "loan_type_auto_loan": 0,
    "loan_type_business_loan": 0,
    "loan_type_credit_card": 0,
    "loan_type_education_loan": 1,
    "loan_type_gold_loan": 0,
    "loan_type_home_loan": 0,
    "loan_type_personal_loan": 0,
    "loan_utilization_ratio": 0.46,
    "location_stability_score": 120,
    "location_type": "Tier1",
    "marital_status": "Single",
    "mobile_app_usage_intensity_score": 79,
    "mobile_banking_usage_score": 95,
    "monthly_business_revenue_inr": 0,
    "monthly_digital_transactions": 69,
    "monthly_expenses_inr": 58576,
    "monthly_income_inr": 77314,
    "monthly_savings_inr": 15754,
    "monthly_utility_bills_inr": 4304,
    "number_of_dependents": 0,
    "outstanding_loan_amount_inr": 775614,
    "payment_reliability_score": 19,
    "probability_of_default": 0.6152,
    "property_value_inr": 0,
    "repayment_ability_score": 26,
    "risk_category": "High Risk",
    "risk_score": 61.5,
    "social_media_accounts_count": 5,
    "spouse_income_inr": 0,
    "stability_index": 34,
    "timeliness_score": 44,
    "total_assets": 284404,
    "total_investments_inr": 158727,
    "utility_payment_regularity_score": 76,
    "vehicle_value_inr": 125677,
    "years_current_employment": 1.9
  },
  {
    "age": 33,
    "applicant_id": "C9952",
    "application_date": "2024-10-15",
    "application_to_income_ratio": 1.5308,
    "avg_transaction_amount_inr": 3726,
    "banking_relationship_years": 17.0,
    "city": "Nadiad",
    "consent_status": "Full Consent",
    "daily_mobile_hours": 7.1,
    "debt_service_coverage": 0.0,
    "digital_payment_adoption_score": 48,
    "education_level": "High School",
    "employment_type": "Business Owner",
    "family_size": 1,
    "financial_health_score": 62,
    "gender": "Female",
    "income_to_expense_ratio": 1.0286,
    "interest_rate": 11.67,
    "loan_amount_applied_inr": 1500000,
    "loan_type": "auto loan",
    "loan_type_auto_loan": 1,
    "loan_type_business_loan": 0,
    "loan_type_credit_card": 0,
    "loan_type_education_loan": 0,
    "loan_type_gold_loan": 0,
    "loan_type_home_loan": 0,
    "loan_type_personal_loan": 0,
    "loan_utilization_ratio": 0.5846,
    "location_stability_score": 120,
    "location_type": "Tier2",
    "marital_status": "Single",
    "mobile_app_usage_intensity_score": 43,
    "mobile_banking_usage_score": 95,
    "monthly_business_revenue_inr": 202208,
    "monthly_digital_transactions": 41,
    "monthly_expenses_inr": 79386,
    "monthly_income_inr": 81659,
    "monthly_savings_inr": 0,
    "monthly_utility_bills_inr": 6689,
    "number_of_dependents": 0,
    "outstanding_loan_amount_inr": 876892,
    "payment_reliability_score": 40,
    "probability_of_default": 0.5362,
    "property_value_inr": 1293287,
    "repayment_ability_score": 37,
    "risk_category": "High Risk",
    "risk_score": 53.6,
    "social_media_accounts_count": 4,
    "spouse_income_inr": 0,
    "stability_index": 79,
    "timeliness_score": 89,
    "total_assets": 1293287,
    "total_investments_inr": 0,
    "utility_payment_regularity_score": 57,
    "vehicle_value_inr": 0,
    "years_current_employment": 15.0
  },
  {
    "age": 34,
    "applicant_id": "A4160",
    "application_date": "2024-09-05",
    "application_to_income_ratio": 5.5556,
    "avg_transaction_amount_inr": 4265,
    "banking_relationship_years": 3.9,
    "city": "Jamnagar",
    "consent_status": "Full Consent",
    "daily_mobile_hours": 8.7,
    "debt_service_coverage": 0.1654,
    "digital_payment_adoption_score": 76,
    "education_level": "Graduate",
    "employment_type": "Professional",
    "family_size": 2,
    "financial_health_score": 10,
    "gender": "Male",
    "income_to_expense_ratio": 2.5193,
    "interest_rate": 9.78,
    "loan_amount_applied_inr": 8000000,
    "loan_type": "home loan",
    "loan_type_auto_loan": 0,
    "loan_type_business_loan": 0,
    "loan_type_credit_card": 0,
    "loan_type_education_loan": 0,
    "loan_type_gold_loan": 0,
    "loan_type_home_loan": 1,
    "loan_type_personal_loan": 0,
    "loan_utilization_ratio": 0.63,
    "location_stability_score": 120,
    "location_type": "Tier1",
    "marital_status": "Married",
    "mobile_app_usage_intensity_score": 68,
    "mobile_banking_usage_score": 95,
    "monthly_business_revenue_inr": 0,
    "monthly_digital_transactions": 57,
    "monthly_expenses_inr": 47632,
    "monthly_income_inr": 120000,
    "monthly_savings_inr": 69457,
    "monthly_utility_bills_inr": 6682,
    "number_of_dependents": 0,
    "outstanding_loan_amount_inr": 5040000,
    "payment_reliability_score": 10,
    "probability_of_default": 0.9201,
    "property_value_inr": 2951965,
    "repayment_ability_score": 5,
    "risk_category": "Very High Risk",
    "risk_score": 92.0,
    "social_media_accounts_count": 3,
    "spouse_income_inr": 30522,
    "stability_index": 5,
    "timeliness_score": 6,
    "total_assets": 4399481,
    "total_investments_inr": 1254876,
    "utility_payment_regularity_score": 25,
    "vehicle_value_inr": 192640,
    "years_current_employment": 16.0
  },
  {
    "age": 45,
    "applicant_id": "E3504",
    "application_date": "2025-07-24",
    "application_to_income_ratio": 2.6583,
    "avg_transaction_amount_inr": 3256,
    "banking_relationship_years": 29.0,
    "city": "Gandhinagar",
    "consent_status": "Full Consent",
    "daily_mobile_hours": 4.6,
    "debt_service_coverage": 0.0,
    "digital_payment_adoption_score": 44,
    "education_level": "Diploma",
    "employment_type": "Salaried",
    "family_size": 1,
    "financial_health_score": 10,
    "gender": "Male",
    "income_to_expense_ratio": 1.1133,
    "interest_rate": 10.05,
    "loan_amount_applied_inr": 1073170,
    "loan_type": "home loan",
    "loan_type_auto_loan": 0,
    "loan_type_business_loan": 0,
    "loan_type_credit_card": 0,
    "loan_type_education_loan": 0,
    "loan_type_gold_loan": 0,
    "loan_type_home_loan": 1,
    "loan_type_personal_loan": 0,
    "loan_utilization_ratio": 0.634,
    "location_stability_score": 120,
    "location_type": "Metro",
    "marital_status": "Single",
    "mobile_app_usage_intensity_score": 45,
    "mobile_banking_usage_score": 81,
    "monthly_business_revenue_inr": 0,
    "monthly_digital_transactions": 28,
    "monthly_expenses_inr": 30217,
    "monthly_income_inr": 33642,
    "monthly_savings_inr": 0,
    "monthly_utility_bills_inr": 4775,
    "number_of_dependents": 0,
    "outstanding_loan_amount_inr": 680374,
    "payment_reliability_score": 10,
    "probability_of_default": 0.8658,
    "property_value_inr": 0,
    "repayment_ability_score": 5,
    "risk_category": "Very High Risk",
    "risk_score": 86.6,
    "social_media_accounts_count": 4,
    "spouse_income_inr": 0,
    "stability_index": 41,
    "timeliness_score": 44,
    "total_assets": 47005,
    "total_investments_inr": 0,
    "utility_payment_regularity_score": 41,
    "vehicle_value_inr": 47005,
    "years_current_employment": 26.8
  },
  {
    "age": 32,
    "applicant_id": "C7457",
    "application_date": "2024-09-20",
    "application_to_income_ratio": 5.0549,
    "avg_transaction_amount_inr": 5680,
    "banking_relationship_years": 16.0,
    "city": "Bharuch",
    "consent_status": "Full Consent",
    "daily_mobile_hours": 7.5,
    "debt_service_coverage": 0.2105,
    "digital_payment_adoption_score": 68,
    "education_level": "Post Graduate",
    "employment_type": "Professional",
    "family_size": 1,
    "financial_health_score": 10,
    "gender": "Male",
    "income_to_expense_ratio": 4.0653,
    "interest_rate": 10.41,
    "loan_amount_applied_inr": 8000000,
    "loan_type": "home loan",
    "loan_type_auto_loan": 0,
    "loan_type_business_loan": 0,
    "loan_type_credit_card": 0,
    "loan_type_education_loan": 0,
    "loan_type_gold_loan": 0,
    "loan_type_home_loan": 1,
    "loan_type_personal_loan": 0,
    "loan_utilization_ratio": 0.6924,
    "location_stability_score": 120,
    "location_type": "Tier2",
    "marital_status": "Single",
    "mobile_app_usage_intensity_score": 76,
    "mobile_banking_usage_score": 95,
    "monthly_business_revenue_inr": 0,
    "monthly_digital_transactions": 42,
    "monthly_expenses_inr": 32441,
    "monthly_income_inr": 131884,
    "monthly_savings_inr": 97188,
    "monthly_utility_bills_inr": 1304,
    "number_of_dependents": 0,
    "outstanding_loan_amount_inr": 5539128,
    "payment_reliability_score": 10,
    "probability_of_default": 0.9065,
    "property_value_inr": 0,
    "repayment_ability_score": 5,
    "risk_category": "Very High Risk",
    "risk_score": 90.6,
    "social_media_accounts_count": 4,
    "spouse_income_inr": 0,
    "stability_index": 5,
    "timeliness_score": 5,
    "total_assets": 0,
    "total_investments_inr": 0,
    "utility_payment_regularity_score": 25,
    "vehicle_value_inr": 0,
    "years_current_employment": 0.5
  }
];

export default DEMO_APPLICANTS;
